<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ADXL3x5Interface" Id="{c139e6f6-f214-44e8-9f0f-a559eda28c47}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ADXL3x5Interface
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ADXL3x5Interface">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>