<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ASIND" Id="{da8c1dfe-65c7-4b94-bf56-5cc6b8382315}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION ASIND : LREAL
VAR_INPUT
	SINVAL:LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ASIND:=RAD_TO_DEG(ASIN(SINVAL));]]></ST>
    </Implementation>
    <LineIds Name="ASIND">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>