<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="COSD" Id="{bb736399-f365-4fea-b648-f1576e601419}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION COSD : LREAL
VAR_INPUT
	ANGLE:LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[COSD:=COS(DEG_TO_RAD(ANGLE));]]></ST>
    </Implementation>
    <LineIds Name="COSD">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>