<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="SIND" Id="{fb5e995e-4182-4df2-b1f8-e15d3e17d758}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION SIND : LREAL
VAR_INPUT
	ANGLE:LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SIND:=SIN(DEG_TO_RAD(ANGLE));]]></ST>
    </Implementation>
    <LineIds Name="SIND">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>